### ISSUE TITLE
"ROLLBACK" query got stuck

### ISSUE THREAD

**Issue by ken-centrality** [subsquid/squid#109]
**Describe the bug**
At the back of #108, I found another issue where the process got stuck [here](https://github.com/subsquid/squid/blob/master/substrate-ingest/src/sink.ts#L290)

**To Reproduce**
1. Follow the step as of #108

**Expected behavior**
Wait for "ROLLBACK" query, if it's longer than X time, ignore

**Comment by eldargab** [comment]
See #111 for explanation.
