### ISSUE TITLE
The `event.evmtxhash` of moonbase network is `null`

### ISSUE THREAD

**Issue by Hayden0323** [subsquid/squid#114]
**Describe the bug**
When testing moonbase, I found that the evmTxHash in the block log message was null.

**To Reproduce**
1. Create a new SubstrateBatchProcessor
2. setDataSource: setDataSource({
    chain: 'wss://wss.api.moonbase.moonbeam.network',
    archive: lookupArchive('moonbase', { release: "FireSquid" })
  })
3. filter block items (item.kind === 'event' && item.name === 'EVM.Log')
4. console.log(item.event.evmTxHash)

**Expected behavior**
evmTxHash should be correct tx hash

**Screenshots**
<img width="701" alt="image" src="https://user-images.githubusercontent.com/57787789/189846266-613e5903-07a2-4868-83d0-04e742a3074d.png">

**Environment (please complete the following information):**
 - specify the version of the core packages (@subsquid/cli, @subsquid/substrate-processor, ...)
 - node.js version
 - npm version
 - OS version
 - Reproducible example or a repo link

**Applicable to decoding issues:**
 - chain name: moonbase
 - typesBundle (if it's not built-in)
optional:
 - block: 2828726
 - extrinsic
 - call
 - event
 - spec version
 - endpoint

**Additional context**

**Comment by belopash** [comment]
Should be fixed by
https://github.com/subsquid/substrate-gateway/commit/ec2c901242bd496db98eabee150689cbed3cc7d6

**Comment by Hayden0323** [comment]
Thanks!
