### ISSUE TITLE
Purpose of Hasura

### ISSUE THREAD

**Issue by ManUtopiK** [subsquid/squid#12]
Hi!
We are currently rebuilding a French blockchain with Substrate, and I would like to use squid to expose a custom graphql API on top of it. I'm new to substrate and just discovered squid, so sorry if my issue looks naïve. However, I've been working with Hasura since tree years, so I'm really enjoyed to see it in your stack!

I read in your doc :
> Subsquid is rapidly deploying Archives to gather data from available blockchains on behalf of developers who wish to use this data to develop DApps.

So, I don't understand why Hasura is on the top of the indexer (Archive)?
The main purpose of Hasura is to build App fast. I need actions, schema remote stitching, events/cron and row/column level permission provided by Hasura to build my awesome DApp. Why Hasura is on the indexer and not a part of the squid api?

Also, we don't need an ORM with Hasura. Hasura is an ORM on top of database!
Why using typeorm in squid to build the graphql api when Hasura could do that out of the box?
Hasura can also build a graphql endpoint on top of many databases. Why not connecting directly the squid database in Hasura? `squid/graphql-server` is useless!
I certainly don't understand well the squid stack, but it seems you are missing out many killer features of Hasura...

Anyway, for now, I used "remote schema" to merge the squid api in Hasura. By this way, I don't have to go to the squid graphiql at port 4350. I just go to Hasura at localhost:4010/console and I got the indexer and squid api merged together. By this way, we can imagine many squid running as microservices, and got one endpoint to fetch them all...

![image](https://user-images.githubusercontent.com/188172/153781705-b2676370-65b5-4664-bda5-ae7ef63d04d0.png)

**Comment by dzhelezov** [comment]
Hey @ManUtopiK 

First of all, thanks a lot for choosing Subsquid for indexing your Substrate data and posting this issue. We definitely considered Hasura and GraphiQL before building OpenReader. Keep in mind that Squid API is designed to be lightweight and easily deployable yet expressive, as we progress towards complete decentralization.

Here's why:
- We wanted a smooth and vertically integrated solution for building the schema, typescript models, migrations and GraphQL API from a single schema file.
- We wanted to have full control of how data is fetched and what GraphQL features we want to support off the shelf. Hasura does not provide a feasible solution to the features we'd like to have. To name a few:
   - Custom scalars with full control of marshalling/unmarshalling (e.g. BigInt, Float. Address scalars)
   - JSONB queries (Hasura offers very limited filtering support)
   - Interfaces and Union types
   - Full-text search support 
- We wanted to support custom GraphQL resolvers/API extensions while keeping it simple and easily portable
- Unified codebase (Typescript)
- Minimal external dependencies to make decentralisation easier (remember, we're not just building a centralized bespoke API but a decentralized marketplace for hosting Squid APIs)

> Also, we don't need an ORM with Hasura. Hasura is an ORM on top of database!
> Why using typeorm in squid to build the graphql api when Hasura could do that out of the box?

I am not sure what you mean here. GraphQL server does not use TypeORM. TypeORM is indeed used under the hood by the Squid Processor, which is an ETL process which runs independently from the presentation layer.  

At the same time it's a totally legit case to use Squid API as a part of a top-level Hasura endpoint or do schema stitching any other way, if it suits you best.

I'm genuinely interested in your use-case and would be happy to discuss more in TG -- feel free to ping me `@dzlzv` on Telegram.
