### ISSUE TITLE
RpcClient error of execution

### ISSUE THREAD

**Issue by Hayden0323** [subsquid/squid#128]
The processor is running fine locally but after uploading to Aquarium gives me this error and keeps stuck around block 1558856, what could be the reason

repo: https://github.com/zenlinkpro/zenlink-astar-subsquid

logs from Aquarium:
![image](https://user-images.githubusercontent.com/57787789/201598468-9bcfb006-a13f-4388-861b-6be9329defa4.png)

local logs
![image](https://user-images.githubusercontent.com/57787789/201598509-8cf6b00b-d213-4787-8ee0-d2553a92f58f.png)

**Comment by belopash** [comment]
https://github.com/zenlinkpro/zenlink-astar-subsquid/blob/fc0181c8e1db84b168097a1939fbb1af319ec5e0/src/consts.ts#L5
Do you have secret with such name? Maybe it refers to another chain?

**Comment by Hayden0323** [comment]
> https://github.com/zenlinkpro/zenlink-astar-subsquid/blob/fc0181c8e1db84b168097a1939fbb1af319ec5e0/src/consts.ts#L5 Do you have secret with such name? Maybe it belongs to another chain?

yes, I used blastapi node when deploying, which is the only difference from local. I'll try to remove the secret and use the default node.

**Comment by belopash** [comment]
Did it help?
