### ISSUE TITLE
squid-evm-typegen 1.3.1 fails with "TypeError: abi.map is not a function"

### ISSUE THREAD

**Issue by abernatskiy** [subsquid/squid#129]
Attempted to use the tool with two smart contracts (`0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9`, the AAVEv2 pool, and `0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413` from [this example](https://docs.subsquid.io/tutorials/create-an-ethereum-processing-squid/)), fails with
```
evm-typegen error: TypeError: abi.map is not a function
```

**To Reproduce**
1. Make a test directory and `cd` to it
2. Run `npm install @subsquid/evm-typegen`
3. Fetch the abi with
```bash
$ curl "https://api.etherscan.io/api?module=contract&action=getabi&address=0xBB9bc244D798123fDe783fCc1C72d3Bb8C189413" --output abi.json
```
4. Run `npx squid-evm-typegen --abi abi.json --output abi.ts`
5. See the error. Note that `abi.ts` is not generated.

**Expected behavior**
Successful generation of `abi.ts`

**Environment (please complete the following information):**
 - node.js version 18.12.1
 - npm version 8.19.2
 - OS version - Gentoo rolling release

**Additional context**
Retrieved [abi.json](https://pastebin.com/raw/MHSVkxV6)

**Comment by belopash** [comment]
Fetched abi has incorrect format

**Comment by abernatskiy** [comment]
Ah I see, `abi.json` is expected to be cleaned up from etherscan metadata. If I do so via
```bash
$ python -c "import json; ifile=open('abi.json', 'r'); print(json.load(ifile)['result']); ifile.close()" > abi2.json
```
then
```bash
$ npx squid-evm-typegen --abi abi2.json --output abi2.ts
```
works.

Thanks.

**Comment by belopash** [comment]
We discussed about "etherscan abi fetch" feature, but not sure if we will implement it.

**Comment by abernatskiy** [comment]
It's not strictly necessary, we'll just have to update the docs with the additional steps. Also, I just discovered [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967) and in light of it etherscan abi fetching will have to be made somewhat more complicated anyway.

**Comment by abernatskiy** [comment]
It would be nice to detect etherscan and format and give the user a hint instead of an opaque error message.
