### ISSUE TITLE
Fix github actions for multi-arch Docker builds

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/squid#21]
More and more people are using M1 Macs, but some x86-64 images do not work on those.

This creates major inconvenience for our M1 users which want to use local indexer, as they have to build gateway image themselves.

Multi-arch docker builds are the way to go - https://docs.docker.com/desktop/multi-arch/.

We need to modify our GitHub docker-build action to produce multi-arch images for x86-64 and ARM.

**Comment by vikiival** [comment]
🥺🥺🥺

**Comment by ma-shulgin** [comment]
https://github.com/subsquid/hydra/pull/185/

**Comment by vikiival** [comment]
Kjuuut ❤️
