### ISSUE TITLE
Metadata not inserts when start ingest from random block.

### ISSUE THREAD

**Issue by zefir01** [subsquid/squid#78]
Hello.

If you start ingest from a non-zero block, for example 11270865, the metadata table will remain empty. Which leads to an error when starting squid.
If you start ingest from the block before changing the metadata, for example 10879370, then the metadata is added to the table.

Please make a check for the presence of the metadata of the first block in the database when starting the ingest, if there is no metadata, then you need to add it.

**Comment by dzhelezov** [comment]
That's a known issue. Currently the workaround is to use `metadata-explorer` directly against a gRPC node as explained [here](https://docs.subsquid.io/docs/guides/migrate-to-fire-squid/#typegen)
