### ISSUE TITLE
An utility lib to convert `polkadot.js` types bundle format to subsquid

### ISSUE THREAD

**Issue by dzhelezov** [subsquid/squid#82]
There's a big pain for new users to use custom types bundle due to the different file format we use compared to `polkadot.js`.
To alleviate this issue, let's make an utility lib that will convert `polkadot.js` bundle files to the subsquid format. We can then reuse this lib so that both the ingester and the typegen will be able to accept `polkadot.js`-style bundle files.

**Comment by eldargab** [comment]
@dzhelezov , how about just built-in support for all networks from polkdot.js.org?

**Comment by dzhelezov** [comment]
Discussed with @belopash and I think we'd still need such a tool:
- it's quite tedious and time consuming to migrate all the networks from polkadot.js/apps/configs
- we had multiple support requests for bundles not present in Polkadot.js/apps/configs (some private networks and devnets)
- having such a tool is need anyway for mass migration from the Polkadot.js format 

So it seems reasonable to just add an additional config options to the ingester, processor and metadata explorer so that they can accept the Polkadot.js format

**Comment by eldargab** [comment]
Solved by https://github.com/subsquid/squid/commit/a4718e1c2ec271a0f8159d8e8c1d296f435ad634
