### ISSUE TITLE
Objects containing Enum fields cause build failures

### ISSUE THREAD

**Issue by theodorebugnet** [subsquid/squid#97]
Consider a schema such as:
```
enum MyEnum {
  A
  B
}

type MyObject {
  enumField: MyEnum!
}
```
`codegen` will then generate a `src/model/generated/_myObject.ts` file, containing a constructor that allows deserializing from JSON using marshal. However, it treats the enum field as a string, causing the typescript build to fail (with the error `Type 'string' is not assignable to type 'MyEnum'.`):

```
  constructor(props?: Partial<Omit<MyObject, 'toJSON'>>, json?: any) {
    Object.assign(this, props)
    if (json != null) {
      this._enumField = marshal.string.fromJSON(json.enumField)
    }
  }
```

I believe the fix would be to generate a type cast for the enum type, e.g.
```
      this._enumField = marshal.string.fromJSON(json.enumField) as MyEnum
```

**Comment by belopash** [comment]
Do you use the latest codegen packege version? This issue has already been fixed.
There should be special function in marshal.ts to deal with enums.
```
export function enumFromJson<E extends object>(json: unknown, enumObject: E): E[keyof E] {
    assert(typeof json == 'string', 'invalid enum value')
    let val = (enumObject as any)[json]
    assert(typeof val == 'string', `invalid enum value`)
    return val as any
}
```
